### PR TITLE
Remove redundant callback in Connection.php

### PR DESCRIPTION
**Pull request by MaartenWaegeman**
Removed the redundant refreshAccessTokenCallback in connect() method in Connection.php
Thanks :)!
See https://github.com/picqer/exact-php-client/pull/449#issuecomment-742474167

### CODE REVIEW

**Comment by stephangroen** [comment]
Waiting on this for the merge in picqer/exact-php-client :)

**Comment by MaartenWaegeman** [comment]
I can make a pullrequest for this commit directly into Picquer if you want @stephangroen if @alexjeen doesn't wake up ;)!

**Comment by stephangroen** [comment]
Yes please @MaartenWaegeman :)

**Comment by alexjeen** [comment]
Sorry I get a lot of review requests on a daily basis so I overlooked this one. Its merged

**Pull request merged**
